pivoting strategy

diff --git a/.github/workflows/tf-format.yaml b/.github/workflows/tf-format.yaml
--- a/.github/workflows/tf-format.yaml
+++ b/.github/workflows/tf-format.yaml
@@ -34,37 +34,10 @@ jobs:
         id: diff_check
         run: |
           if [[ -s diff.txt ]]; then
-            cat diff.txt
-            echo "TERRAFORM_DIFF=true" >> $GITHUB_ENV
-            echo "DIFF_CONTENT<<EOF" >> $GITHUB_OUTPUT
-            cat diff.txt >> $GITHUB_OUTPUT
-            echo "EOF" >> $GITHUB_OUTPUT
+            echo "::error file=diff.txt::formatting changes found"
+            echo $(cat diff.txt)
+            exit 1
           else
             echo "TERRAFORM_DIFF=false" >> $GITHUB_ENV
           fi
 
-      - name: post diff to PR
-        if: ${{ env.TERRAFORM_DIFF == 'true' }}
-        uses: actions/github-script@v7
-        with:
-          script: |
-            const diffContent = `${{ steps.diff_check.outputs.DIFF_CONTENT }}`;
-            const commentBody = `
-
-              CI detected formatting possibilities in the terraform files in this repo. 
-              Please review and adjust accordingly.
-
-              <details>
-                <summary> View diff here </summary>
-
-                ${diffContent}
-
-              </details>
-            `;
-
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: commentBody
-            });
